# Generated by Django 6.0.2 on 2026-04-04 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название машины')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('oil_change_interval', models.IntegerField(default=50000, verbose_name='Интервал замены масла (км)')),
                ('tire_change_interval', models.IntegerField(default=60000, verbose_name='Интервал замены резины (км)')),
                ('last_oil_change_km', models.IntegerField(default=0, verbose_name='Последняя замена масла на пробеге (км)')),
                ('last_tire_change_km', models.IntegerField(default=0, verbose_name='Последняя замена резины на пробеге (км)')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.IntegerField(verbose_name='Километры')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='portal.car', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
                'ordering': ['-date'],
            },
        ),
    ]
